version: '3.1'

services:
  app:
    build: .
    container_name: loopback-app
    restart: always
    environment:
      HOST: 0.0.0.0
      PORT: 3001
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: postgres
    container_name: prj4
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
